image: jakobbraun/midiplayer-linux-build-env
  
client:
  script:
    - cd client
    - qmake
    - make
  artifacts:
    paths:
      - client/client
    
server:
  script:
    - cd server
    - qmake
    - make
