addons:
  apt:
    sources:
      - sourceline: 'deb http://httpredir.debian.org/debian jessie main'
      - sourceline 'deb http://httpredir.debian.org/debian jessie-updates main'
      - sourceline 'deb http://security.debian.org jessie/updates main'
    packages:
     - build-essential 
     - qt5-default
     - qtbase5-dev
     - qtdeclarative5-dev
     - libqt5websockets5-dev
     - qtmultimedia5-dev
     - libjack-jackd2-dev
     - libaubio-dev
     - libola-dev
     - libprotobuf-dev
  
script:
  -cd client
  - qmake
  - make

deploy:
  provider: releases
  api_key: "$GH_API_KEY"
  file: "client/client"
  skip_cleanup: true
  on:
    tags: true
