FROM debian
#RUN zypper ref && zypper in -y libqt5-qtquick1-deve llibqt5-qtwebsockets-devel
RUN apt-get update && apt-get -y install build-essential qt5-default qtbase5-dev  qtdeclarative5-dev libqt5websockets5-dev qtmultimedia5-dev  libjack-jackd2-dev libaubio-dev libola-dev libprotobuf-dev
